### ISSUE TITLE
HasLog lacks a functional dependency

### ISSUE THREAD

**Issue by peti** [kowainik/co-log#132]
I believe the `HasLog env msg m` class lacks a functional dependency from `env` to `msg`. Without it, this trivial code won't typecheck:

~~~
newLogger :: (MonadReader env m, HasLog env msg m) => m ()
newLogger = local (setLogAction undefined) (return ())
~~~

**Comment by peti** [comment]
For reference, check out the class that `lens` generates for the  following code:

~~~
newtype LogAction m msg = LogAction { _runLogAction :: msg -> m ()  }

makeClassy ''LogAction
~~~

Gives:

~~~
class HasLogAction c (m :: * -> *) msg | c -> m msg where
  logAction :: Lens' c (LogAction m msg)
  runLogAction :: Lens' c (msg -> m ())
  {-# MINIMAL logAction #-}
~~~

**Comment by chshersh** [comment]
@peti Absence of a functional dependency from `env` to `msg` is intentional. Otherwise, it wouldn't be possible to have multiple log actions inside a single environment. See the following example:

https://github.com/kowainik/co-log/blob/c5b897d503f6d71662fbbd88210171e6a0e5f8a4/co-log/tutorials/Main.hs#L144-L147

Instead of manually using `local` you can use `withLog` function provided by the `co-log`. Will it resolve your issue?

https://github.com/kowainik/co-log/blob/c5b897d503f6d71662fbbd88210171e6a0e5f8a4/co-log/src/Colog/Monad.hs#L76-L77

**Comment by peti** [comment]
> Absence of a functional dependency from `env` to `msg` is intentional. Otherwise, it wouldn't be possible to have multiple log actions inside a single environment.

OK, I see. It appears that we have different design goals then. The ability to log different message types in the same monad is not important to me (especially not if I need explicit type annotations to do it). My loggers all take a ByteString builder. On the other hand, the ability to manipulate the reader's environment with standard MonadReader functions is important to me. What's the point of having the MonadReader abstraction if the generic functions don't work properly? I'd rather make an effort to design the environment in such a way that it doesn't cause trouble with the type system. That's more valuable to me than having the additional flexibility (that I don't need anyway). 

Just my 2 cents.
