### ISSUE TITLE
Beginner friendly aliases

### ISSUE THREAD

**Issue by NickSeagull** [kowainik/co-log#155]
Hi, I mentioned [on Twitter](https://twitter.com/NickSeagull/status/1179405198965510144) about this issue, I'm opening it here so it is easier to track.

The idea would be to provide aliases for functions that a user would use a lot. Like for example

```haskell
formatWith = contramap
```

so it is easier for newcomers to pick up. This follows the principle of least surprise, both for beginners and experts.

The motivation is the same as having `List.singleton`, instead of writing:

```haskell
pure . pure . pure
```

one can write:

```haskell
pure . Just . singleton
```

which is more readable

**Comment by chshersh** [comment]
Hi @NickSeagull, in general, I don't mind. And I can see how this can be useful. Probably, for this function to make more sense it should have the following more specialized type:

```haskell
formatWith :: (msg -> Text) -> LogAction m Text -> LogAction m msg
```

And this means that it should go to `co-log` package directly (because `co-log-core` currently depends only on `base`). But it can be a useful alias :slightly_smiling_face: PR is welcome!

**Comment by NickSeagull** [comment]
Thanks!
