### ISSUE TITLE
Combining log and printf

### ISSUE THREAD

**Issue by mb720** [kowainik/co-log#178]
Hi!

I'm having a great time with `co-log`! 👍

In my application, I often create formatted strings using [`printf`](https://hackage.haskell.org/package/base-4.12.0.0/docs/Text-Printf.html#v:printf) and pass them to `co-log`'s `log`:

    import qualified Data.Text as T ( pack )

    log W $ T.pack $ printf "Something went wrong: %s\n" msg

and

    log I $ T.pack $ printf "Some values: %d, %s, %s\n" i x y

I tried to wrap this up in a helper function:

    logF
      :: forall env (m :: * -> *) sev
      . (MonadReader env m, HasLog env (Msg sev) m)
      => sev
      -> String
      -> m ()
    logF severity msg = log severity $ T.pack $ printf msg

But this version of `logF` conflicts with `printf` having a variable number of arguments and my Haskell skills are not yet at the level to fix this.

Is there a viable way of combining `log` and `printf` as attempted with `logF` above?

**Comment by chshersh** [comment]
@mb720 Thanks for your kind words about `co-log`! 😊 I see how users of logging can benefit from using some string interpolation capabilities. Unfortunately, it's not possible to have both `printf`-like capabilities and the `log` function polymorphic over return type. Because of the magic used by the `printf` function, you can't have `m ()` as a return type in `log`. So it is **not possible** to achieve the following

```haskell
log I "Some values: %d, %s, %s\n" i x y
```

without some dramatic changes to the `co-log` API. The closest you can get in terms of code is by writing your own `logString` function which takes `String`, calls `log` with `T.pack` and you'll use this function like this:

```haskell
logString I $ printf "Some values: %d, %s, %s\n" i x y
```

Aside from the issue, I want to add that using `String` in general is a bad idea performance-wise. And using this particular `printf` is discouraged, since it's not type-safe and can bring some debugging nightmares after some simple refactoring (I had a similar problem once in production). Also, `printf` is extremely slow. That's why I don't see immediate need to implement first-class support for `printf` in `co-log`. If you're interested in fast string interpolation with low syntactic noise, I can recommend a formatting library like [`fmt`](https://github.com/neongreen/fmt) (though it's not maintained at the moment) or [`neat-interpolation`](https://hackage.haskell.org/package/neat-interpolation) package.

In long term there will be out-of-the-box support for structured logging in `co-log` since this is the standard was of doing logging in applications. I only have some ideas on my mind how to implement this in `co-log`. Some tangentially relevant issues:

* https://github.com/kowainik/co-log/issues/28
* https://github.com/kowainik/co-log/issues/93

**Comment by chshersh** [comment]
Closing this in favour of #179, since the only workaround is described in this issue, not much can be done on the `co-log` side to improve the situation, and a more principled solution would be _structured logging_.

**Comment by mb720** [comment]
Just as an inspiration for your future implementation: [a type-safe printf](https://github.com/mstksg/typelits-printf)
