### ISSUE TITLE
`filterBySeverity` may bring unexpected extra computation on `Msg` due to strictness?

### ISSUE THREAD

**Issue by Commelina** [kowainik/co-log#197]
Sometimes we want to filter some log messages by `filterBySeverity`. What we expect is that if a messages is filtered, the action will not be executed at all. However, the pre-defined message types `Msg`, `SimpleMsg` and `Message` have a [strict `!Text` field](https://github.com/kowainik/co-log/blob/17d91e47cf3850a9e9f879f2bd9c01e661f13e28/co-log/src/Colog/Message.hs#L109), which can bring unexpected computation on message we want to log.

For example:

```haskell
level :: MonadIO m
      => Colog.LogAction m Colog.Message
level = Colog.filterBySeverity Colog.I sev Colog.richMessageAction
  where sev Colog.Msg{..} = msgSeverity

app :: App ()
app = do
  let veryLongMsg = Text.replicate 100000000 "aaaaa"
  Colog.logDebug veryLongMsg
  Colog.logInfo  "bbbbb"
```

In this example, I do not want `logDebug` to be executed. However due to the strictness, `veryLongMsg` will be computed instead of being lazy. This slightly goes against the semantics of `filterBySeverity` and can bring performance problems sometimes.

So I want to know if the strict mark is for special usage and if the behavior above is a bug or just an improper use of the library.

**Comment by chshersh** [comment]
The strict annotation for `msgBody` was added to avoid space-leaks. But I can see how having a lazy message body text can be beneficial in the context of filtering messages. Feel free to open a PR :slightly_smiling_face: I believe, marking the `msgText` field as non-strict should solve the problem.

**Comment by 4eUeP** [comment]
@chshersh Should we just remove the strict annotation of`msgText` in place (this means we will lack of avoiding space-leaks)? Or create a `New-Msg` data type that has non-strict `msgText` ? ( Or any other elegant way to dealing with this ?

**Comment by chshersh** [comment]
@4eUeP I think removing the strict annotation of `msgText` is the way to go. Usually, you want all fields of your data types be strict. This is a good default that helps avoiding space leaks. However, very rare you want to have lazy fields explicitly. Fortunately, in Haskell it's quite easy to make fields lazy 🙂 And it seems that logging is one of those rare use cases.

Consider the following code:

```haskell
foo = do
    ...
    let groupedUsers = groupBy userId users
    log Debug $ "Grouped users:\n" <> prettyShow groupedUsers
```

The `groupBy` operation can be potentially slow, and we want to avoid doing in it production. So, with proper lazy Haskell you can write the above code and don't worry about this slow function being called, because all `Debug` messages will be simply discarded. For this to work, we need to have lazy messages fields.

Of course, `co-log` is very flexible, and you can easily implement your own message types. But currently it's not that straightforward to easily reuse other `co-log` functions with your own message types. We're planning to work on structured logging #179 for the next release, and we will strive to make all functions and types even more flexible. But for now, having a lazy `msgText` field sounds like a good and idiomatic solution 👍
