### ISSUE TITLE
Consider removing Colog.Concurrent or updating it to the upstream version

### ISSUE THREAD

**Issue by qnikst** [kowainik/co-log#214]
Hello! April 16 in a private conversation I was kindly asked to move `Colog.Concurrent.*` to a separate package and maintain it on my own and told that the next version of `co-log` will no longer contain those modules. I did that in 2 days, fixing a few problems along the way.

Since that time there was at least one release but modules are still there as well as in main branch. While I'm perfectly fine with the code being duplicated in `co-log`, it would be nice to update them to the same versions as in upstream. As currently Web search shows `co-log` version above the `co-log-concurrent` one, so users may end up with a broken version.

Thanks!

**Comment by qnikst** [comment]
Actually there is a ticket #187 about this issue, so I can close this one. Still there is an issue that `co-log-concurrent` package has bug fixes (with an internal API change).

**Comment by vrom911** [comment]
As requested by you, we agreed to return you the code you contributed so that you can have your own separate repo independently from us.

As @chshersh mentioned, a new major release of co-log won't have these modules. We do follow PVP and are not going to make exceptions. When the new release is ready, it won't contain your code, as you requested in private conversation.
